platforms:
  feishu:
    enabled: true
    extra:
      connection_mode: websocket

mcp_servers:
  kwiki:
    url: "https://zhishi.wps.cn/personalwiki/kwiki_mcp/mcp"
    headers:
      X-Kwiki-Auth: "9dEIo2l/QYACRw/KbTgC3GoaVqM2kK0JejtNcowyTIdvXa1t36c8OJ/elXXcrp5gCyd8e0hZjNAwyntRYpmaFAPkwIbHd/To9RKVpLdSlRyqyFHm09fbBJQGlZTzepnXbg1POdISZcsjO+/g8Q=="
      X-Skill-Version: "1.0.0"
    timeout: 120
